services:
  admin-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adminapi
    environment:
      - DATABASE_URL=postgresql://admin:admin123@admin-database:5432/adminapidb
      - SECRET_KEY=admin123
    ports:
      - "8000:8000"
    depends_on:
      admin-database:
        condition: service_healthy  
    restart: always
    volumes:
      - ./:/app

  admin-database:
    image: postgres:15
    container_name: admin-database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d adminapidb"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=adminapidb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: